name: Publish Docker image
on:
  push:
    branches:
      - main
  schedule:
    - cron: 37 * * * *
  workflow_dispatch: {}

env:
  dockerhub_tag: pahud/gitpod-workspace:latest
  ghcr_tag: ghcr.io/pahud/gitpod-workspace:latest

jobs:
  docker_hub:
    name: Docker Hub
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:
      - name: Get short SHA
        id: sha
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .gitpod.Dockerfile
          tags: |
            ${{github.repository}}:latest
            ${{github.repository}}:${{ steps.sha.outputs.sha7 }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  # github_container:
  #   name: Github Container Registry
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get short SHA
  #       id: sha
  #       run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.CR_PAT }}
  #     - name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         file: .gitpod.Dockerfile
  #         tags: |
  #           ghcr.io/${{github.repository}}:latest
  #           ghcr.io/${{github.repository}}:${{ steps.sha.outputs.sha7 }}
  #     - name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}
  ecr_public:
    name: ECR Public
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:
      - name: Get repo name
        id: repoName
        run: echo "::set-output name=reponame::$(echo ${{github.repository}} | cut -d '/' -f 2)"
      - name: Get short SHA
        id: sha
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - name: Build and Push to ECR Public
        id: build-and-push
        uses: pahud/ecr-public-action@8cd826db40befb59b0cd0b60b22a7ba72d06a7f7
        with:
          dockerfile: .gitpod.Dockerfile
          tags: |
            public.ecr.aws/pahudnet/${{ steps.repoName.outputs.reponame }}:latest
            public.ecr.aws/pahudnet/${{ steps.repoName.outputs.reponame }}:${{ steps.sha.outputs.sha7 }}
